version: '3.7'

services:
  wp-and-db-storage:
    image: alpine:3.11.6
    volumes:
      - db_data:/storage/var_lib_mysql
      - wp_data:/storage/var_www_html

  db:
    depends_on:
      - wp-and-db-storage
    image: mysql:${MYSQL_VERSION}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_UNIT_VERSION=${PHP_UNIT_VERSION}
        - WP_VERSION=${WP_VERSION}
    ports:
      - "8123:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
    volumes:
      - wp_data:/var/www/html

  wordpress-cli:
    depends_on:
      - wordpress
    image: wordpress:cli
    user: xfs
    command: >
      /bin/sh -c '
        sleep 10; \
        wp core install \
          --path="/var/www/html" \
          --url="wordpress" \
          --title="Plugin e2e tests" \
          --admin_user=admin \
          --admin_password=secret \
          --admin_email=foo@bar.com;
      '
    volumes:
      - wp_data:/var/www/html

  e2e-test:
    image: cypress/included:4.5.0
    depends_on:
      - wordpress
    environment:
      - CYPRESS_baseUrl=http://wordpress
      - ELECTRON_ENABLE_LOGGING=true
    working_dir: /e2e
    entrypoint: bash -c "npm run test:e2e"
    volumes:
      - e2e_data:/e2e

volumes:
  db_data:
  e2e_data:
  wp_data:
