version: 2.1

jobs:
  e2e_test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build images
          command: |
            cd e2e-tests
            docker-compose up --build --no-start
      - run:
          name: Install Wordpress
          command: |
            cd e2e-tests
            docker-compose run wordpress-cli
      - run:
          name: Install WordPress Plugin
          command: |
            cd e2e-tests
            docker cp ../ "$(docker-compose ps -q wordpress)":/var/www/html/wp-content/plugins/my-plugin
            docker exec -ti "$(docker-compose ps -q wordpress)" sh -c "cd /var/www/html/wp-content/plugins/my-plugin && composer update --prefer-lowest && composer install"
      - run:
          name: Run linter
          command: |
            cd e2e-tests
            docker exec -ti "$(docker-compose ps -q wordpress)" sh -c "cd /var/www/html/wp-content/plugins/my-plugin && ./vendor/bin/phpcs --report=junit --report-file=phpcs-results.xml"
            mkdir -p ../test-results/phpcs
            docker cp "$(docker-compose ps -q wordpress)":/var/www/html/wp-content/plugins/my-plugin/phpcs-results.xml ../test-results/phpcs/results.xml || true
      - run:
          name: Run unit tests
          command: |
            cd e2e-tests
            docker exec -ti "$(docker-compose ps -q wordpress)" sh -c "cd /var/www/html/wp-content/plugins/my-plugin && bash bin/install-wp-tests.sh wordpress_test root 'somewordpress' db latest"
            docker exec -ti "$(docker-compose ps -q wordpress)" sh -c "cd /var/www/html/wp-content/plugins/my-plugin && ./vendor/bin/phpunit --log-junit phpunit-results.xml"
      - run:
          when: always
          name: Fetch unit test results
          command: |
            mkdir -p test-results/phpunit
            cd e2e-tests
            docker cp "$(docker-compose ps -q wordpress)":/var/www/html/wp-content/plugins/my-plugin/phpunit-results.xml ../test-results/phpunit/results.xml || true
      - run:
          name: Run e2e tests
          command: |
            cd e2e-tests
            docker cp ./ "$(docker-compose ps -q e2e-test)":/e2e
            docker-compose run e2e-test
      - run:
          when: always
          name: Fetch e2e test results
          command: |
            mkdir -p artifacts/cypress
            mkdir -p test-results/cypress
            cd e2e-tests
            docker cp "$(docker-compose ps -q e2e-test)":/e2e/cypress cypress-results || true
            mv cypress-results/screenshots cypress-results/videos -t ../artifacts/cypress/ || true
            mv cypress-results/xml ../test-results/cypress || true
      - store_artifacts:
          path: artifacts
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - e2e_test
