version: 2.1

jobs:
  e2e_test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build images
          command: |
            cd e2e-tests
            docker-compose up --no-start --force-recreate  --build
      - run:
          name: Install Wordpress
          command: |
            cd e2e-tests
            docker-compose run wordpress-cli
      - run:
          name: Install composer
          command: |
            cd e2e-tests
            docker exec -ti "$(docker-compose ps -q wordpress)" sh -c "apt-get update && apt-get install curl && curl -s https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer"
      - run:
          name: Install WordPress Plugin
          command: |
            cd e2e-tests
            docker cp ../ "$(docker-compose ps -q wordpress)":/var/www/html/wp-content/plugins/my-plugin
            docker exec -ti "$(docker-compose ps -q wordpress)" sh -c "cd /var/www/html/wp-content/plugins/my-plugin && composer install"
      - run:
          name: Run unit tests
          command: |
            cd e2e-tests
            docker exec -ti "$(docker-compose ps -q wordpress)" sh -c "apt-get install subversion"
            docker exec -ti "$(docker-compose ps -q wordpress)" sh -c "cd /var/www/html/wp-content/plugins/my-plugin && bash bin/install-wp-tests.sh wordpress_test root 'somewordpress' localhost latest"
            docker exec -ti "$(docker-compose ps -q wordpress)" sh -c "cd /var/www/html/wp-content/plugins/my-plugin && ./vendor/bin/phpunit --log-junit ./junit.xml tests"
      - run:
          when: always
          name: Fetch unit test results
          command: |
            mkdir -p unit-tests/xml
            cd e2e-tests
            docker cp "$(docker-compose ps -q wordpress)":/var/www/html/wp-content/plugins/my-plugin/junix.xml ../unit-tests/xml/junix.xml
      - store_test_results:
          path: unit-tests/xml
      - run:
          name: Run e2e tests
          command: |
            cd e2e-tests
            docker cp ./ "$(docker-compose ps -q e2e-test)":/e2e
            docker-compose run e2e-test
      - run:
          when: always
          name: Fetch e2e test results
          command: |
            cd e2e-tests
            docker cp "$(docker-compose ps -q e2e-test)":/e2e/cypress .
      - store_artifacts:
          path: e2e-tests/cypress/videos
      - store_artifacts:
          path: e2e-tests/cypress/screenshots
      - store_test_results:
          path: e2e-tests/cypress/xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - e2e_test
