version: 2.1

commands:
  restore_and_start_wp:
    description: Restore installation and start WordPress
    parameters:
      mysql-version:
        type: string
        default: "5.6"
      php-version:
        type: string
        default: "5.6"
      php-unit-version:
        type: string
        default: "5.7.20"
      wp-version:
        type: string
        default: "5"
    steps:
      - attach_workspace:
          at: /tmp/workspace/storage
      - setup_remote_docker
      - checkout
      - run:
          name: Restore installation
          command: |
            docker-compose up -d wp-and-db-storage
            docker cp /tmp/workspace/storage/. "$(docker-compose ps -q wp-and-db-storage)":/storage
      - run:
          name: Start WordPress
          environment:
            - MYSQL_VERSION: << parameters.mysql-version >>
            - PHP_VERSION: << parameters.php-version >>
            - PHP_UNIT_VERSION: << parameters.php-unit-version >>
            - WP_VERSION: << parameters.wp-version >>
          command: |
            docker-compose up -d wordpress
            sleep 10

jobs:
  build-php56: &build-template
    docker:
      - image: cimg/base:2020.01
    environment:
      - MYSQL_VERSION: "5.6"
      - PHP_VERSION: "5.6"
      - PHP_UNIT_VERSION: "5.7.20"
      - WP_VERSION: "5"
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install WordPress
          command: |
            docker-compose up wordpress-cli
      - run:
          name: Install WordPress Plugin
          command: |
            echo "php unit version: ${PHP_UNIT_VERSION}"
            docker cp . "$(docker-compose ps -q wordpress)":/var/www/html/wp-content/plugins/my-plugin
            docker exec -ti "$(docker-compose ps -q wordpress)" \
              sh -c "cd /var/www/html/wp-content/plugins/my-plugin && \
                composer update --prefer-lowest && \
                composer install"
      - run:
          name: Fetch installation data
          command: |
            mkdir -p /tmp/workspace
            docker cp "$(docker-compose ps -q wp-and-db-storage)":/storage/. /tmp/workspace/storage
      - persist_to_workspace:
          root: /tmp/workspace/storage
          paths:
            - var_www_html
            - var_lib_mysql

  build-php70:
    <<: *build-template
    environment:
      - MYSQL_VERSION: "5.6"
      - PHP_VERSION: "7.0"
      - PHP_UNIT_VERSION: "5.7.20"
      - WP_VERSION: "5"

  build-php71:
    <<: *build-template
    environment:
      - MYSQL_VERSION: "5.6"
      - PHP_VERSION: "7.1"
      - PHP_UNIT_VERSION: "5.7.20"
      - WP_VERSION: "5"

  build-php72:
    <<: *build-template
    environment:
      - MYSQL_VERSION: "5.6"
      - PHP_VERSION: "7.2"
      - PHP_UNIT_VERSION: "8"
      - WP_VERSION: "5"

  build-php73:
    <<: *build-template
    environment:
      - MYSQL_VERSION: "5.6"
      - PHP_VERSION: "7.3"
      - PHP_UNIT_VERSION: "8"
      - WP_VERSION: "5"

  linter:
    docker:
      - image: cimg/base:2020.01
    steps:
      - restore_and_start_wp
      - run:
          name: Run linter
          command: |
            docker exec -ti "$(docker-compose ps -q wordpress)" \
              sh -c "cd /var/www/html/wp-content/plugins/my-plugin && \
                ./vendor/bin/phpcs --report=junit --report-file=phpcs-results.xml"
      - run:
          when: always
          name: Fetch linter results
          command: |
            mkdir -p /tmp/workspace/test-results/phpcs
            docker cp "$(docker-compose ps -q wordpress)":/var/www/html/wp-content/plugins/my-plugin/phpcs-results.xml /tmp/workspace/test-results/phpcs/results.xml || true
      - store_test_results:
          path: /tmp/workspace/test-results/phpcs

  unit_tests:
    docker:
      - image: cimg/base:2020.01
    steps:
      - restore_and_start_wp
      - run:
          name: Setup unit test environment
          command: |
            docker exec -ti "$(docker-compose ps -q wordpress)" \
              sh -c "cd /var/www/html/wp-content/plugins/my-plugin && \
                bash bin/install-wp-tests.sh wordpress_test root 'somewordpress' db latest"
      - run:
          name: Run unit tests
          command: |
            docker exec -ti "$(docker-compose ps -q wordpress)" \
              sh -c "cd /var/www/html/wp-content/plugins/my-plugin && \
                ./vendor/bin/phpunit --log-junit phpunit-results.xml"
      - run:
          when: always
          name: Fetch unit test results
          command: |
            mkdir -p /tmp/workspace/test-results/phpunit
            docker cp "$(docker-compose ps -q wordpress)":/var/www/html/wp-content/plugins/my-plugin/phpunit-results.xml /tmp/workspace/test-results/phpunit/results.xml || true
      - store_test_results:
          path: /tmp/workspace/test-results/phpunit

  e2e_tests:
    docker:
      - image: cimg/base:2020.01
    steps:
      - restore_and_start_wp
      - run:
          name: Run e2e tests
          environment:
            - MYSQL_VERSION: 5.6
            - PHP_VERSION: 5.6
            - PHP_UNIT_VERSION: 5.7.20
            - WP_VERSION: 5
          command: |
            docker-compose up --no-start e2e-test
            docker cp ./e2e-tests/. "$(docker-compose ps -q e2e-test)":/e2e
            docker-compose run e2e-test
      - run:
          when: always
          name: Fetch e2e test results
          command: |
            mkdir -p /tmp/workspace/artifacts/cypress
            mkdir -p /tmp/workspace/test-results/cypress
            docker cp "$(docker-compose ps -q e2e-test)":/e2e/cypress cypress-results || true
            mv cypress-results/screenshots cypress-results/videos -t /tmp/workspace/artifacts/cypress/ || true
            mv cypress-results/xml /tmp/workspace/test-results/cypress || true
      - store_artifacts:
          path: /tmp/workspace/artifacts
      - store_test_results:
          path: /tmp/workspace/test-results/cypress

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-php56
      - build-php70
      - build-php71
      - build-php72
      - build-php73
      - linter:
          requires:
            - build-php56
      - unit_tests:
          requires:
            - linter
      - e2e_tests:
          requires:
            - unit_tests
