version: 2.1

jobs:
  e2e_test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: copy e2e dir to cypress container and run tests
          command: |
            cd e2e-tests
            docker cp ./ "$(docker-compose ps -q e2e-test)":/e2e
            docker-compose up --exit-code-from e2e-test e2e-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - e2e_test
