version: 2.1
 
references:
  # Environment variables
  #
  WP_CORE_DIR: &WP_CORE_DIR
    /tmp/wordpress
  WP_HOST: &WP_HOST
    localdev.local
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
    wp-reading-time-2020
  WP_ORG_USERNAME: &WP_ORG_USERNAME
    idleherb
 
  # Default container configuration
  #
  container_config: &container_config
    docker:
      - image: circleci/php:7.2
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
    working_directory: ~/wp-reading-time-2020
 
  workspace_root: &workspace_root
    /tmp
 
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
 
  copy_vendor: &copy_vendor
    run:
      name: Copy vendor directory
      command: cp -R /tmp/vendor .
 
  # Default configuration for e2e tests with cypress
  #
  e2e_tests_job: &e2e_tests_job
    <<: *container_config
    docker:
      - image: circleci/php:7.2-node
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run:
          name: Add WordPress host to hosts file
          command: echo "127.0.0.1 ${WP_HOST}" | sudo tee -a /etc/hosts
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Install MySQL client
          command: sudo apt-get install mysql-client
      - run:
          name: Install MySQL PHP extension
          command: sudo docker-php-ext-install mysqli
      - run:
          name: Setup WordPress
          command: .circleci/setup-$WP_TYPE.sh
      - run:
          name: Start PHP server
          command: sudo php -S $WP_HOST:80 -t $WP_CORE_DIR
          background: True
      - run:
          name: Install cypress
          command: npm install --global cypress
      - run:
          name: Run e2e tests
          command: vendor/bin/behat --config .circleci/behat.yml --format progress --tags=$WP_TYPE
 
  # Default configuration for all phpunit testing jobs
  #
  phpunit_job: &phpunit_job
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Run PHP unit tests
          command: vendor/bin/phpunit
 
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install -n -o
      - run:
          name: Install WordPress
          command: bash .circleci/install-wp.sh
      - persist_to_workspace:
          root: .
          paths:
            - vendor
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - wordpress
 
  linter:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Run linter
          command: vendor/bin/phpcs
 
  unit_test_php74:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.4
 
  unit_test_php73:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.3
 
  unit_test_php72:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.2
 
  e2e_tests:
    <<: *e2e_tests_job
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
      - WP_TYPE: singlesite
 
  deploy_assets:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *install_subversion
      - run:
          name: Deploy assets to WordPress plugin directory
          command: .circleci/deploy-assets.sh
 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy_assets:
          filters:
            branches:
              only:
                - master
      - linter:
          requires:
            - build
      - unit_test_php74:
          requires:
            - linter
      - unit_test_php73:
          requires:
            - linter
      - unit_test_php72:
          requires:
            - linter
      - e2e_tests:
          requires:
            - unit_test_php74
            - unit_test_php73
            - unit_test_php72

