version: 2.1

jobs:
  e2e_test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: copy e2e dir to cypress container and run tests
          command: |
            cd e2e-tests
            docker-compose up --no-start --force-recreate  --build
            docker cp ./ "$(docker-compose ps -q e2e-test)":/e2e
            docker-compose run e2e-test
      - store_artifacts:
          path: e2e/cypress/videos
      - store_artifacts:
          path: e2e/cypress/screenshots
      - store_artifacts:
          path: e2e/cypress/logs
      - store_test_results:
          path: e2e/cypress/xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - e2e_test
