version: '3.6'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:5.4.1-php7.3-apache
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
    # add shared volume
    volumes:
      - wp_data:/var/www/html
      - ..:/var/www/html/wp-content/plugins/my-plugin
    networks:
      default:
        aliases:
          - wptests

  wordpress-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    # This is required to run wordpress-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    user: xfs
    # The sleep 10 is required so that the command is run after
    # mysql is initialized. Depending on your machine this might take
    # longer or it can go faster.
    command: >
      /bin/sh -c '
      sleep 10;
      wp core install --path="/var/www/html" --url="wordpress.test" --title="Local Wordpress By Docker" --admin_user=admin --admin_password=secret --admin_email=foo@bar.com
      '
    # add shared volume
    volumes:
      - wp_data:/var/www/html

  e2e-test:
    image: cypress/included:4.5.0
    depends_on:
      - wordpress-cli
      - wordpress
      - db
    environment:
      - CYPRESS_BASEURL=http://wptests
      - ELECTRON_ENABLE_LOGGING=true
    working_dir: /e2e
    entrypoint: bash -c "npm run e2e:docker-compose"
    volumes:
      - ./cypress:/e2e
      - ./cypress.json:/e2e/cypress.json

volumes:
  db_data:
  wp_data:
